# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PGenConfig.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PGenConfig.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10PGenConfig.proto\"\xb3\x01\n\x14GeneralConfiguration\x12\x12\n\nEntityType\x18\x01 \x01(\x05\x12\x15\n\rNexusProtVers\x18\x02 \x01(\t\x12\x16\n\x0eUnitStatusCode\x18\x03 \x01(\x05\x12\x18\n\x10UnitSerialNumber\x18\x04 \x01(\t\x12\x10\n\x08\x43linicId\x18\x06 \x01(\x05\x12\x16\n\x0eOperatorIdList\x18\x07 \x01(\t\x12\x14\n\x0cOperatorType\x18\t \x01(\x05\x62\x06proto3'
)




_GENERALCONFIGURATION = _descriptor.Descriptor(
  name='GeneralConfiguration',
  full_name='GeneralConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='EntityType', full_name='GeneralConfiguration.EntityType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NexusProtVers', full_name='GeneralConfiguration.NexusProtVers', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UnitStatusCode', full_name='GeneralConfiguration.UnitStatusCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UnitSerialNumber', full_name='GeneralConfiguration.UnitSerialNumber', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ClinicId', full_name='GeneralConfiguration.ClinicId', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OperatorIdList', full_name='GeneralConfiguration.OperatorIdList', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OperatorType', full_name='GeneralConfiguration.OperatorType', index=6,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=200,
)

DESCRIPTOR.message_types_by_name['GeneralConfiguration'] = _GENERALCONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralConfiguration = _reflection.GeneratedProtocolMessageType('GeneralConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _GENERALCONFIGURATION,
  '__module__' : 'PGenConfig_pb2'
  # @@protoc_insertion_point(class_scope:GeneralConfiguration)
  })
_sym_db.RegisterMessage(GeneralConfiguration)


# @@protoc_insertion_point(module_scope)
