# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PGenConfig2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PGenConfig2.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11PGenConfig2.proto\"\xad\x01\n\x14GeneralConfiguration\x12\x12\n\nEntityType\x18\x01 \x01(\x05\x12\x15\n\rNexusProtVers\x18\x02 \x01(\t\x12\x16\n\x0eUnitStatusCode\x18\x03 \x01(\x05\x12\x15\n\rUnitDisplayId\x18\x04 \x01(\t\x12\x10\n\x08\x43linicId\x18\x06 \x01(\x05\x12\x18\n\x10PT_DisplayIdList\x18\x07 \x01(\t\x12\x0f\n\x07UnitUID\x18\x08 \x01(\tb\x06proto3')
)




_GENERALCONFIGURATION = _descriptor.Descriptor(
  name='GeneralConfiguration',
  full_name='GeneralConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='EntityType', full_name='GeneralConfiguration.EntityType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NexusProtVers', full_name='GeneralConfiguration.NexusProtVers', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UnitStatusCode', full_name='GeneralConfiguration.UnitStatusCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UnitDisplayId', full_name='GeneralConfiguration.UnitDisplayId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ClinicId', full_name='GeneralConfiguration.ClinicId', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PT_DisplayIdList', full_name='GeneralConfiguration.PT_DisplayIdList', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UnitUID', full_name='GeneralConfiguration.UnitUID', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['GeneralConfiguration'] = _GENERALCONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralConfiguration = _reflection.GeneratedProtocolMessageType('GeneralConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _GENERALCONFIGURATION,
  '__module__' : 'PGenConfig2_pb2'
  # @@protoc_insertion_point(class_scope:GeneralConfiguration)
  })
_sym_db.RegisterMessage(GeneralConfiguration)


# @@protoc_insertion_point(module_scope)
